
import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className={`${poppins.className} bg-[#020617] text-slate-100 antialiased`}>
          {/* <Header /> */}
          <Header />

          <main className="min-h-screen ">{children}</main>

          <Toaster position="top-center" />

          {/* <Footer /> */}
          <Footer />
        </body>
    </html>
  );
}
